# Generated by Django 4.1.3 on 2022-11-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentiment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inputstring",
            name="sentiment",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
